### ISSUE TITLE
Some small bugs in Spire front end

### ISSUE THREAD

**Issue by cherudim9** [csyonghe/Spire#10]
Xor operator `^` is not processed in `ParseOperators()`. (https://github.com/csyonghe/Spire/blob/master/Source/SpireCore/Lexer.cpp#L55)

**Comment by cherudim9** [comment]
Also, regarding lexer, the question mark `?` should be added into the list in `IsPunctuation()` (https://github.com/csyonghe/Spire/blob/master/Source/SpireCore/Lexer.cpp#L24).

**Comment by cherudim9** [comment]
In compiler front end, select instructions are not being properly processed. 
On https://github.com/csyonghe/Spire/blob/master/Source/SpireCore/CodeGenerator.cpp#L713 , in the end of `VisitSelectExpression()`, an expression should be pushed into expression stack.

**Comment by csyonghe** [comment]
bugs fixed. Thanks!
