### ISSUE TITLE
[VulkanEngine] GameEngine.sln missing

### ISSUE THREAD

**Issue by SaschaWillems** [csyonghe/Spire#15]
The [readme](https://github.com/csyonghe/Spire/blob/master/Examples/VulkanEngine/Readme.md) for the Vulkan engine refers to a GameEngine.sln which is not present in the repo.

Can this be added to the repository? Without it one has to guess what libraries to build in which order and where to put them to get this up and running. The GameEngienCore project also won't compile due to VK_CPP_TYPESAFE_CONVERSION not being set which I guess is done in the missing .sln.

**Comment by csyonghe** [comment]
The file is now uploaded. Thanks for pointing this out.
