### ISSUE TITLE
Output file path (not just file name) in error messages

### ISSUE THREAD

**Issue by tangent-vector-personal** [csyonghe/Spire#16]
If I invoke the Spire compiler as:

```
SpireCompiler.exe .\foo\bar\baz.spire
```

and I get an error message, it is formatted without the path:

```
baz.spire(99): error 33023: argument ...
```

This makes it so that I can't double-click on the error message in my editor and go to the line, because the error message seems to refer to a non-existent file.

**Comment by csyonghe** [comment]
this is fixed.
