### ISSUE TITLE
Spire doesn't seem to output "undefined identifier" errors

### ISSUE THREAD

**Issue by tangent-vector-personal** [csyonghe/Spire#17]
If I write some code that uses an undefined variable (or I just spell it wrong) I get:

```
error 30017: component 'foo' is not accessible from shader 'Test'
```

Similarly, if I try to call a function that is undefined I get:

   error 30021: Foo: no overload takes arguments (int)

It would seem a bit nicer to have clear errors for the case where there is _nothing_ of the given name in scope, and reserve the errors above for cases where there is something in-scope but it is not accessible or applicable in the current context for one reason or another.

**Comment by csyonghe** [comment]
this is fixed.
