### ISSUE TITLE
Allow functions to be defined inside shaders/modules

### ISSUE THREAD

**Issue by tangent-vector-personal** [csyonghe/Spire#18]
It is a pretty common idiom in HLSL/GLSL code to have functions that receive some inputs through their ordinary parameter list, but that also depend on shader inputs (uniforms, textures, etc.) that were declared at the global scope.

When porting to Spire, we can either translate these functions into a module (which has its own issues), or keep them a function, but in the latter case it seems like we have to make all the parameters explicit for now, because we can't nest a function inside a module or shader (at least it didn't work when I tried).

This seems like an important feature to have, although it could have thorny interactions with placement constraints.

**Comment by csyonghe** [comment]
This feature is added in latest update.
