### ISSUE TITLE
Can't `require` a `sampler2d`

### ISSUE THREAD

**Issue by tangent-vector-personal** [csyonghe/Spire#20]
I've been using `require` statements to work around the lack of explicit inter-module interfaces (see #19), but now found that if I try to use:

```
require sampler2d someSampler;
```

I get an error:

```
error 33035: 'someSampler': sampler, struct and array types only allowed in input worlds
```

This seems like an oversight in the case of a `require`, since this simply results in a placement constraint such that the component will only ever land in an input world.

I'm also not sure why there would be a ban on `struct` or array types in non-input worlds, but I figure I can file a bug against those if and when they become a problem.

**Comment by csyonghe** [comment]
this is fixed.
