### ISSUE TITLE
Operator `*=` yields an error.

### ISSUE THREAD

**Issue by tangent-vector** [csyonghe/Spire#22]
I had code inside a component like:

```
vec4 foo = ...;
foo.rgb *= foo.a;
```

and I got an error on the `*=` operator, about there being no available overload.

I worked around the issue by changing the code to not use a compound assignment operator:

```
foo.rgb = foo.rgb * foo.a;
```

Thus is appears that the issue may be as simple as compound assignment operators being unimplemented (?).

**Comment by csyonghe** [comment]
This is because vector.xyz (swizzling) is currently a right-value so you cannot assign values to it.

**Comment by csyonghe** [comment]
this is now supported.
