### ISSUE TITLE
No `tex2Dproj` function

### ISSUE THREAD

**Issue by tangent-vector** [csyonghe/Spire#24]
This is a builtin function in older HLSL (and I believe also in GLSL). This is probably just a matter of adding it as a builtin, but we probably need to take a pass and either systematically add all the texture-fetch operations we need, or start working on using unparsed HLSL/GLSL strings.

**Comment by csyonghe** [comment]
textureProj(sampler2D, vec3 p)
function is added.

**Comment by tangent-vector** [comment]
The newly added `textureProj` overloads incorrectly return `float` instead of `vec4` when called on an ordinary `sampler2D` (rather than a `sampler2DShadow`).
