### ISSUE TITLE
No support for HLSL "method call" syntax on samplers

### ISSUE THREAD

**Issue by tangent-vector** [csyonghe/Spire#25]
The D3D10+ HLSL `Texture2D` and related resource types use C#-ish method-call syntax, e.g.:

```
int3 pixelCoord = int3(x,y, 0);
float4 val = someTexture.Load( pixelCoord );
```

This syntax fails to parse in Spire. This could be worked around if Spire decides to support the same basic operations as ordinary functions, rather than members.

**Comment by csyonghe** [comment]
texelFetch(sampler2D tex, ivec2 coord, int lod);
function is added.
