### ISSUE TITLE
Visibility rules for `public` components

### ISSUE THREAD

**Issue by tangent-vector** [csyonghe/Spire#28]
It seems like the rules for what components are visible to a `using` are "recursive" so that if I have:

```
module Nested { public float foo = 1.0; }
module Wrapper { using Nested; }

module UsesFoo { require float foo; }
```

then the following works:

```
module Works
{
    // `Wrapper` doesn't export anything, but `Nested` does
    using Wrapper;

    // Automatically satisifies the `Foo` requirement using the `foo` in `Nested`
    using UsesFoo;
}
```

However, the same "recursive" rules don't seem to apply when I try to just use `foo` directly:

```
module DoesntWork
{
    using Wrapper;

    // I get an error on this line, because `foo` isn't defined here
    float bar = foo + 1.0;
}
```

This is a little bit confusing on the face of it, and I also can't really see a workaround, that would allow the `Wrapper` module to somehow "re-export" a component output by something nested in it.

I mean, I guess that I could make `Wrapper` use an explicit `using` and then do a named export:

```
module Wrapper
{
     using n : Nested;
    public float foo = n.foo;
}
```

But that seems like a really kludgy workaround. Maybe a nice syntax would be to allow `public using` to automatically re-export everything that was public in the sub-module?

```
module Wrapper { public using Nested; }
```

Any sort of guidelines here (even just "don't do that") would be appreciated.

**Comment by csyonghe** [comment]
"public using Nested;" is supposed to work. If it does not, that is a bug. I'll look into this.

Actually, automatic parameter matching should not succeed because foo should not be visible to scope of module Works. You need "public using Nested" to make foo visible. The fact that Works passes compilation is a compiler bug.

**Comment by tangent-vector** [comment]
I had not known that `public using` was an implemented feature. Thanks for educating me. :)
