### ISSUE TITLE
Crash in x64 version inside `MByteToWideChar`

### ISSUE THREAD

**Issue by tangent-vector** [csyonghe/Spire#3]
It looks like the problem is that you are declaring and `int`:

```
int bufferSize;
```

and then passing a pointer to it where a `size_t*` is expected:

```
mbstowcs_s((size_t*)&bufferSize, ...);
```

This pattern is repeated for the variable `pos` later in the same function.

Changing both of these to `size_t` seems to eliminate the crash for me, but leaves me wondering whether I should be trying to use Spire in a 64-bit project...

**Comment by csyonghe** [comment]
This is solved. Spire is supposed to run on 64 bit platform. 
The bug was introduced during a port to Ubuntu.
