### ISSUE TITLE
add HLSL backend

### ISSUE THREAD

**Issue by csyonghe** [csyonghe/Spire#32]

**Comment by tangent-vector** [comment]
I'll take this one.

The trivial/naive way to do this would be to copy-paste the existing `GLSLCodeGen.cpp`, and then tweak it until it works, but that is going to make for more maintenance work whenever changes affect both (and even more if we also add source code output for Metal).

My plan is to introduce an intermediate base class `CLikeCodeGen` that inherits from `CodeGenBackend` and  which both GLSL and HLSL code gen can inherit from (and eventually Metal, if we want it).

**Comment by csyonghe** [comment]
This sounds like a good idea, but I have a feeling that it may get more involved then expected and turn out to be defining another layer of language independent constructs.

On Tue, Nov 8, 2016 at 11:57 AM -0500, "Tim Foley" <notifications@github.com<mailto:notifications@github.com>> wrote:

I'll take this one.

The trivial/naive way to do this would be to copy-paste the existing GLSLCodeGen.cpp, and then tweak it until it works, but that is going to make for more maintenance work whenever changes affect both (and even more if we also add source code output for Metal).

My plan is to introduce an intermediate base class CLikeCodeGen that inherits from CodeGenBackend and which both GLSL and HLSL code gen can inherit from (and eventually Metal, if we want it).

**Comment by tangent-vector** [comment]
The initial refactoring is in place, and Spire can now produce HLSL for a completely trivial vertex/fragment shader. I am working on getting a minimal "hello world" D3D example in place (using the C API) before I start picking additional test cases to try out.

**Comment by tangent-vector** [comment]
Pull request #48 made things quite a bit less non-trival, and also added support for Hull/Domain shaders.

Remaining major issues are:
- Compute shader support (these can't really be handled together with vertex/domain/fragment like the GL path tries to)
- Adding a lot of missing built-in semantics, functions, etc.

I suppose I will keep this issue open for now, but we might consider closing it in favor or more fine-grained issues for the detailed work left to be done.

**Comment by csyonghe** [comment]
closing this issue and will file more specific issues for future changes.
