### ISSUE TITLE
Vertex shader `gl_Position` output being passed to fragment shader unnecessarily

### ISSUE THREAD

**Issue by tangent-vector** [csyonghe/Spire#39]
If I declare a simple vertex + fragment shader, then I find that the `projCoord` computed in my vertex shader is being declared as a VS output and an FS input, even though the value is never used in the FS.

It seems like the logic for determining which components are "live" coming out of a stage needs to understand that system-consumed "outputs" in a given stage do not actual make the corresponding component live-out (although they do make it "live" from a DCE perspective).

**Comment by csyonghe** [comment]
I think I have already fixed this issue, probably I haven't checked them in. I'll make sure this is fixed in the next commit.

**Comment by tangent-vector** [comment]
This issue has been resolved, and I can confirm the fix. Closing.
