### ISSUE TITLE
No implicit type conversion (even for literals)?

### ISSUE THREAD

**Issue by tangent-vector** [csyonghe/Spire#4]
This might be closed as "by design," but I was a bit surprised when I had the equivalent of:

   vec3 P = ...;
   vec4 P_homogeneous = vec4(P, 1);

The compiler informed me that there was no overload for `(vec3, int)`, and of course I fixed the issue by changing the `1` to `1.0`.

Note that I'd imported the expression in question by copy-pasting the GLSL I started with, so small issues like this will probably irk new users more than people who write in Spire from scratch.

**Comment by csyonghe** [comment]
Added implicit type conversion from int to float in function invocations.
