### ISSUE TITLE
Two copies of Spire.h?

### ISSUE THREAD

**Issue by tangent-vector** [csyonghe/Spire#44]
There appear to be two identical files in the repository:

    Source/SpireLib/include/Spire.h
    LibraryRelease/Spire.h

It isn't immediately clear to me as somebody looking at the repository which of these would be the one I'm supposed to include in a user project, and which I'm supposed to edit if I want to make changes.

It would be a lot more obvious to just have `include/spire.h`, and no additional copies. The "packaging" step makes some amount of sense for the .cpp distribution (although we still need to address the issues of people editing generated code), but it makes almost no sense for the .h.

**Comment by csyonghe** [comment]
LibraryRelease/Spire.h is removed.
We need to tell people who are looking for single-file source code library where to find the header file though.
