### ISSUE TITLE
No vector * matrix product?

### ISSUE THREAD

**Issue by tangent-vector** [csyonghe/Spire#6]
It seems like Spire supports `M * v`, but not `v * M`.

This is a bit annoying for me because my mini app is using a row-major layout for its matrices, and rather than transposing them when filling in a uniform buffer, it is just reversing the order of multiplication in the GLSL shaders.

I can work around this (especially if `transpose()` is supported in Spire), but it would be nice to have this just work out of the box.

(I guess another issue along those lines is whether I can affect the default matrix layout convention for the generated GLSL...).

**Comment by csyonghe** [comment]
This is supported now.
