### ISSUE TITLE
Moving to spire-lang?

### ISSUE THREAD

**Issue by polarathene** [csyonghe/Spire#85]
Is future development to remain at this repo, or will it be moving to [spire-lang](https://github.com/spire-lang/Spire)?

**Comment by tangent-vector-personal** [comment]
Thanks for asking this. We haven't been very clear about communicating the future plans for the project code. It would be good if Yong weighs in on this (he may see things differently from me), but the way I understand things:

- The `csyonghe/Spire` is what you want if you need to reproduce the work from the SIGGRAPH 2016 Spire paper.

- The `spire-lang/Spire` repository represents the Spire system as presented at SIGGRAPH 2017. 

- Ongoing development of those forks is not planned, and instead we have a more production-oriented fork of the code at `shader-slang/Slang`.

That last fork has had a lot of follow-on development, and now supports a lot of existing HLSL code. Along the way, however, it dropped a lot of the new ideas introduced in the Spire research. My plan is to add back the most important capabilities from Spire to the "Slang" codebase, but in a way that supports gradual evolution from an HLSL codebase.

So if you asked *me* I'd say that all new development, issues, and PRs should go to `shader-slang/Slang` unless they specifically relate to one of the Spire research papers. Yong may see it differently.

**Comment by polarathene** [comment]
It'd be great if that could be communicated in the repo description or as a note on the README for the sigrraph repos. I came across the 2017 repo via whitepaper link via phoronix article. So it'd aid discovery for the repo where actual development is going on at :)

**Comment by tangent-vector-personal** [comment]
I agree with your advice, but I think I should let @csyonghe make any actual changes. Yong, is it reasonable to add a forwarding message in both of the Spire repositories that points to Slang as the place where active development is occurring?

**Comment by csyonghe** [comment]
Thanks for the advice. The readme has been updated.
